// <auto-generated />
using System;
using Guestly.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guestly.Migrations
{
    [DbContext(typeof(GuestlyContext))]
    [Migration("20210127193034_PlaceOfOrigin")]
    partial class PlaceOfOrigin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Guestly.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Guestly.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("LifetimeNights");

                    b.Property<int>("LifetimeRevenue");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            City = "Lynchburg",
                            Country = "United States",
                            Email = "jd@email.com",
                            FirstName = "Jack",
                            LastName = "Daniel",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "1223334444",
                            State = "TN"
                        },
                        new
                        {
                            GuestId = 2,
                            City = "Albuquerque",
                            Country = "United States",
                            Email = "thisisdrew@email.com",
                            FirstName = "Drew",
                            LastName = "Mason",
                            LifetimeNights = 1,
                            LifetimeRevenue = 220,
                            PhoneNumber = "5673451231",
                            State = "NM"
                        },
                        new
                        {
                            GuestId = 3,
                            City = "Arlington",
                            Country = "United States",
                            Email = "matthewpatel@email.com",
                            FirstName = "Matthew",
                            LastName = "Patel",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "192837465",
                            State = "VA"
                        },
                        new
                        {
                            GuestId = 4,
                            City = "Boston",
                            Country = "United States",
                            Email = "sethdoray@email.com",
                            FirstName = "Seth",
                            LastName = "Doray",
                            LifetimeNights = 5,
                            LifetimeRevenue = 750,
                            PhoneNumber = "5033505003",
                            State = "MA"
                        },
                        new
                        {
                            GuestId = 5,
                            City = "Laredo",
                            Country = "United States",
                            Email = "doublerich@email.com",
                            FirstName = "Richard",
                            LastName = "Richardson",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "9717717771",
                            State = "TX"
                        },
                        new
                        {
                            GuestId = 6,
                            City = "Seattle",
                            Country = "United States",
                            Email = "cal3b3dwards@email.com",
                            FirstName = "Caleb",
                            LastName = "Edwards",
                            LifetimeNights = 2,
                            LifetimeRevenue = 190,
                            PhoneNumber = "2736498710",
                            State = "WA"
                        },
                        new
                        {
                            GuestId = 7,
                            City = "Karasuno",
                            Country = "Japan",
                            Email = "volleyballrox@email.com",
                            FirstName = "Shoyo",
                            LastName = "Hinita",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "1133224433",
                            State = "Miyagi"
                        },
                        new
                        {
                            GuestId = 8,
                            City = "Fresno",
                            Country = "United States",
                            Email = "rileykeys@email.com",
                            FirstName = "Riley",
                            LastName = "Keys",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "4252075079",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 9,
                            City = "Washington",
                            Country = "United States",
                            Email = "heyyouparkit@email.com",
                            FirstName = "Parker",
                            LastName = "Wallenburger",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "5555599999",
                            State = "DC"
                        },
                        new
                        {
                            GuestId = 10,
                            City = "Tulsa",
                            Country = "United States",
                            Email = "mydognigel@email.com",
                            FirstName = "Nigel",
                            LastName = "Dogo",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "3333333333",
                            State = "OK"
                        },
                        new
                        {
                            GuestId = 11,
                            City = "Tampa",
                            Country = "United States",
                            Email = "rickiede@email.com",
                            FirstName = "Rick",
                            LastName = "Ellis",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "4155558956",
                            State = "FL"
                        },
                        new
                        {
                            GuestId = 12,
                            City = "Greensboro",
                            Country = "United States",
                            Email = "acathome@email.com",
                            FirstName = "Alex",
                            LastName = "Calder",
                            LifetimeNights = 1,
                            LifetimeRevenue = 95,
                            PhoneNumber = "5065558989",
                            State = "NC"
                        },
                        new
                        {
                            GuestId = 13,
                            City = "Nashville",
                            Country = "United States",
                            Email = "elbell@email.com",
                            FirstName = "Erica",
                            LastName = "Bell",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "9715558562",
                            State = "TN"
                        },
                        new
                        {
                            GuestId = 14,
                            City = "Pittsburgh",
                            Country = "United States",
                            Email = "denicolab@email.com",
                            FirstName = "Bobby",
                            LastName = "DeNicola",
                            LifetimeNights = 5,
                            LifetimeRevenue = 550,
                            PhoneNumber = "7075559846",
                            State = "PA"
                        },
                        new
                        {
                            GuestId = 15,
                            City = "Riverside",
                            Country = "United States",
                            Email = "emmunoz@email.com",
                            FirstName = "Ellie",
                            LastName = "Munoz",
                            LifetimeNights = 3,
                            LifetimeRevenue = 255,
                            PhoneNumber = "5035556231",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 16,
                            City = "Toledo",
                            Country = "United States",
                            Email = "jmcteller@email.com",
                            FirstName = "Joshua",
                            LastName = "McTeller",
                            LifetimeNights = 2,
                            LifetimeRevenue = 170,
                            PhoneNumber = "4155558894",
                            State = "OH"
                        },
                        new
                        {
                            GuestId = 17,
                            City = "St. Paul",
                            Country = "United States",
                            Email = "nnatell@email.com",
                            FirstName = "Natalie",
                            LastName = "Lass",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "5415558896",
                            State = "MN"
                        },
                        new
                        {
                            GuestId = 18,
                            City = "Detroit",
                            Country = "United States",
                            Email = "tridoublep@email.com",
                            FirstName = "Tripp",
                            LastName = "Ford",
                            LifetimeNights = 4,
                            LifetimeRevenue = 500,
                            PhoneNumber = "5035552483",
                            State = "MI"
                        },
                        new
                        {
                            GuestId = 19,
                            City = "Cleveland",
                            Country = "United States",
                            Email = "wilford@email.com",
                            FirstName = "Willie",
                            LastName = "Ford",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "4155556472",
                            State = "OH"
                        },
                        new
                        {
                            GuestId = 20,
                            City = "Sacramento",
                            Country = "United States",
                            Email = "katwoz@email.com",
                            FirstName = "Kaitlin",
                            LastName = "Wozniak",
                            LifetimeNights = 3,
                            LifetimeRevenue = 375,
                            PhoneNumber = "5035558258",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 21,
                            City = "San Antonio",
                            Country = "United States",
                            Email = "madalynl11@email.com",
                            FirstName = "Madalyn",
                            LastName = "Lathem",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "6514553861",
                            State = "TX"
                        },
                        new
                        {
                            GuestId = 22,
                            City = "Las Vegas",
                            Country = "United States",
                            Email = "sean.mercado04@email.com",
                            FirstName = "Sean",
                            LastName = "Mercado",
                            LifetimeNights = 1,
                            LifetimeRevenue = 125,
                            PhoneNumber = "5018988936",
                            State = "NV"
                        },
                        new
                        {
                            GuestId = 23,
                            City = "New Orleans",
                            Country = "United States",
                            Email = "viktoriaaksnes@email.com",
                            FirstName = "Viktoria",
                            LastName = "Nielsen",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "7843247148",
                            State = "LA"
                        },
                        new
                        {
                            GuestId = 24,
                            City = "Garland",
                            Country = "United States",
                            Email = "now@email.com",
                            FirstName = "Nao",
                            LastName = "Oka",
                            LifetimeNights = 5,
                            LifetimeRevenue = 425,
                            PhoneNumber = "3193198947",
                            State = "TX"
                        },
                        new
                        {
                            GuestId = 25,
                            City = "Montgomery",
                            Country = "United States",
                            Email = "bernie@mittens.com",
                            FirstName = "Bernie",
                            LastName = "Hancock",
                            LifetimeNights = 3,
                            LifetimeRevenue = 255,
                            PhoneNumber = "2778649180",
                            State = "AB"
                        },
                        new
                        {
                            GuestId = 26,
                            City = "Oakland",
                            Country = "United States",
                            Email = "pratte16@email.com",
                            FirstName = "Eleanor",
                            LastName = "Pratte",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "4529407334",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 27,
                            City = "Boise",
                            Country = "United States",
                            Email = "aurorabergen@email.com",
                            FirstName = "Aurora",
                            LastName = "Berg",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "1338214188",
                            State = "ID"
                        },
                        new
                        {
                            GuestId = 28,
                            City = "The Shire",
                            Country = "Middle Earth",
                            Email = "mr.underhill@email.com",
                            FirstName = "Frodo",
                            LastName = "Baggins",
                            LifetimeNights = 4,
                            LifetimeRevenue = 380,
                            PhoneNumber = "5385970949",
                            State = "Eriador"
                        },
                        new
                        {
                            GuestId = 29,
                            City = "Tokyo",
                            Country = "Japan",
                            Email = "takanoart@email.com",
                            FirstName = "Aya",
                            LastName = "Takano",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "2969397018",
                            State = "Tokyo"
                        },
                        new
                        {
                            GuestId = 30,
                            City = "Chula Vista",
                            Country = "United States",
                            Email = "deckard.rick@email.com",
                            FirstName = "Rick",
                            LastName = "Deckard",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "6192533993",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 31,
                            City = "Vancouver",
                            Country = "Canada",
                            Email = "happy_golfmore@email.com",
                            FirstName = "Happy",
                            LastName = "Gilmore",
                            LifetimeNights = 2,
                            LifetimeRevenue = 190,
                            PhoneNumber = "1234578900",
                            State = "BC"
                        },
                        new
                        {
                            GuestId = 32,
                            City = "San Diego",
                            Country = "United States",
                            Email = "joycesummers@email.com",
                            FirstName = "Joyce",
                            LastName = "Summers",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "1987899876",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 33,
                            City = "Durham",
                            Country = "United States",
                            Email = "KHarm123@email.com",
                            FirstName = "Harmony",
                            LastName = "Kendall",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "1465768945",
                            State = "NC"
                        },
                        new
                        {
                            GuestId = 34,
                            City = "Reno",
                            Country = "United States",
                            Email = "JennyCal@email.com",
                            FirstName = "Jenny",
                            LastName = "Calendar",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "2343546754",
                            State = "NV"
                        },
                        new
                        {
                            GuestId = 35,
                            City = "Long Beach",
                            Country = "United States",
                            Email = "anointed1_66@email.com",
                            FirstName = "Annointed",
                            LastName = "One",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "6894562341",
                            State = "CA"
                        },
                        new
                        {
                            GuestId = 36,
                            City = "Portland",
                            Country = "United States",
                            Email = "H.Sums@email.com",
                            FirstName = "Hank",
                            LastName = "Summers",
                            LifetimeNights = 2,
                            LifetimeRevenue = 300,
                            PhoneNumber = "1029384234",
                            State = "OR"
                        },
                        new
                        {
                            GuestId = 37,
                            City = "Atlanta",
                            Country = "United States",
                            Email = "jessekmcjay@email.com",
                            FirstName = "Jesse",
                            LastName = "McNally",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "4675823123",
                            State = "GA"
                        },
                        new
                        {
                            GuestId = 38,
                            City = "Adelaide",
                            Country = "South Africa",
                            Email = "JonLev@email.com",
                            FirstName = "Jonathan",
                            LastName = "Levinson",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "9858673452",
                            State = "Eastern Cape"
                        },
                        new
                        {
                            GuestId = 39,
                            City = "ekuPhakameni",
                            Country = "South Africa",
                            Email = "eRayne@email.com",
                            FirstName = "Ethan",
                            LastName = "Rayne",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "2384655432",
                            State = "KwaZulu-Natal"
                        },
                        new
                        {
                            GuestId = 40,
                            City = "Hillcrest",
                            Country = "South Africa",
                            Email = "gottahavefaith@email.com",
                            FirstName = "Faith",
                            LastName = "Lehane",
                            LifetimeNights = 3,
                            LifetimeRevenue = 330,
                            PhoneNumber = "2349853456",
                            State = "KwaZulu-Natal"
                        },
                        new
                        {
                            GuestId = 41,
                            City = "Montpellier",
                            Country = "France",
                            Email = "notTaratino@email.com",
                            FirstName = "Quentin",
                            LastName = "Travers",
                            LifetimeNights = 12,
                            LifetimeRevenue = 1020,
                            PhoneNumber = "3458768676",
                            State = "Occitanie"
                        },
                        new
                        {
                            GuestId = 42,
                            City = "Nantes",
                            Country = "France",
                            Email = "scott!@email.com",
                            FirstName = "Scott",
                            LastName = "Hope",
                            LifetimeNights = 1,
                            LifetimeRevenue = 150,
                            PhoneNumber = "5436667534",
                            State = "Pays de la Loire"
                        },
                        new
                        {
                            GuestId = 43,
                            City = "Nice",
                            Country = "France",
                            Email = "asYouWish@email.com",
                            FirstName = "Wesley",
                            LastName = "Pryce",
                            LifetimeNights = 4,
                            LifetimeRevenue = 600,
                            PhoneNumber = "2345674564",
                            State = "Cote d'Azure"
                        },
                        new
                        {
                            GuestId = 44,
                            City = "Marseille",
                            Country = "France",
                            Email = "PromQueen@email.com",
                            FirstName = "Cordelia",
                            LastName = "Chase",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "5543234321",
                            State = "Bouches-du-Rhone"
                        },
                        new
                        {
                            GuestId = 45,
                            City = "Paris",
                            Country = "France",
                            Email = "OnlyBuffyWillJudge@email.com",
                            FirstName = "Buffy",
                            LastName = "Summers",
                            LifetimeNights = 13,
                            LifetimeRevenue = 1105,
                            PhoneNumber = "8778887634",
                            State = "Ile-de-France"
                        },
                        new
                        {
                            GuestId = 46,
                            City = "Istanbul",
                            Country = "Turkey",
                            Email = "Bookguy@email.com",
                            FirstName = "Rupert",
                            LastName = "Giles",
                            LifetimeNights = 2,
                            LifetimeRevenue = 170,
                            PhoneNumber = "4756566879",
                            State = "Istanbul"
                        },
                        new
                        {
                            GuestId = 47,
                            City = "Ankara",
                            Country = "Turkey",
                            Email = "witchStuff@email.com",
                            FirstName = "Willow",
                            LastName = "Rosenberg",
                            LifetimeNights = 1,
                            LifetimeRevenue = 95,
                            PhoneNumber = "7998884475",
                            State = "Ankara"
                        },
                        new
                        {
                            GuestId = 48,
                            City = "Izmir",
                            Country = "Turkey",
                            Email = "jokesDotCom@email.com",
                            FirstName = "Xander",
                            LastName = "Harris",
                            LifetimeNights = 4,
                            LifetimeRevenue = 600,
                            PhoneNumber = "3334958679",
                            State = "Izmir"
                        },
                        new
                        {
                            GuestId = 49,
                            City = "Bursa",
                            Country = "Turkey",
                            Email = "BadBois@email.com",
                            FirstName = "William",
                            LastName = "Pratt",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "4445556634",
                            State = "Bursa"
                        },
                        new
                        {
                            GuestId = 50,
                            City = "Adana",
                            Country = "Turkey",
                            Email = "ImaMouse@email.com",
                            FirstName = "Amy",
                            LastName = "Madison",
                            LifetimeNights = 3,
                            LifetimeRevenue = 285,
                            PhoneNumber = "2873345543",
                            State = "Adana"
                        },
                        new
                        {
                            GuestId = 51,
                            City = "Milan",
                            Country = "Italy",
                            Email = "TwoNewtons@email.com",
                            FirstName = "Cassie",
                            LastName = "Newton",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "9987896786",
                            State = "Lombardy"
                        },
                        new
                        {
                            GuestId = 52,
                            City = "Naples",
                            Country = "Italy",
                            Email = "Alternate@email.com",
                            FirstName = "Chao",
                            LastName = "Ahn",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "6675844776",
                            State = "Campania"
                        },
                        new
                        {
                            GuestId = 53,
                            City = "Turin",
                            Country = "Italy",
                            Email = "SeattleResident@email.com",
                            FirstName = "Count",
                            LastName = "Dracula",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "9980987867",
                            State = "Piedmont"
                        },
                        new
                        {
                            GuestId = 54,
                            City = "Palermo",
                            Country = "Italy",
                            Email = "militarystuff@email.com",
                            FirstName = "Forrest",
                            LastName = "Gates",
                            LifetimeNights = 5,
                            LifetimeRevenue = 425,
                            PhoneNumber = "8009978865",
                            State = "Cicily"
                        },
                        new
                        {
                            GuestId = 55,
                            City = "Rome",
                            Country = "Italy",
                            Email = "Indiacohen@email.com",
                            FirstName = "India",
                            LastName = "Cohen",
                            LifetimeNights = 3,
                            LifetimeRevenue = 330,
                            PhoneNumber = "9078788986",
                            State = "Lazio"
                        },
                        new
                        {
                            GuestId = 56,
                            City = "Peristeri",
                            Country = "Greece",
                            Email = "janicePenshaw@email.com",
                            FirstName = "Janice",
                            LastName = "Penshaw",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "6678745632",
                            State = "Attica"
                        },
                        new
                        {
                            GuestId = 57,
                            City = "Larissa",
                            Country = "Greece",
                            Email = "KathyNewman@email.com",
                            FirstName = "Kathy",
                            LastName = "Newman",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "1122212345",
                            State = "Thessaly"
                        },
                        new
                        {
                            GuestId = 58,
                            City = "Patras",
                            Country = "Greece",
                            Email = "KendraYoung@email.com",
                            FirstName = "Kendra",
                            LastName = "Young",
                            LifetimeNights = 4,
                            LifetimeRevenue = 500,
                            PhoneNumber = "4645534233",
                            State = "Western Greece"
                        },
                        new
                        {
                            GuestId = 59,
                            City = "Thessaloniki",
                            Country = "Greece",
                            Email = "BeelzebubRules@email.com",
                            FirstName = "Hades",
                            LastName = "Beelzebub",
                            LifetimeNights = 5,
                            LifetimeRevenue = 550,
                            PhoneNumber = "6666666666",
                            State = "Macedonia"
                        },
                        new
                        {
                            GuestId = 60,
                            City = "Jersey City",
                            Country = "United States",
                            Email = "TheJenny@email.com",
                            FirstName = "Jenny",
                            LastName = "Jenny",
                            LifetimeNights = 3,
                            LifetimeRevenue = 375,
                            PhoneNumber = "2018675309",
                            State = "NJ"
                        });
                });

            modelBuilder.Entity("Guestly.Models.GuestRoom", b =>
                {
                    b.Property<int>("GuestRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GuestId");

                    b.Property<int>("Nights");

                    b.Property<int>("RoomId");

                    b.HasKey("GuestRoomId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("GuestRoom");

                    b.HasData(
                        new
                        {
                            GuestRoomId = 1,
                            GuestId = 1,
                            Nights = 2,
                            RoomId = 1
                        },
                        new
                        {
                            GuestRoomId = 2,
                            GuestId = 2,
                            Nights = 1,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 3,
                            GuestId = 3,
                            Nights = 4,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 4,
                            GuestId = 4,
                            Nights = 5,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 5,
                            GuestId = 5,
                            Nights = 3,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 6,
                            GuestId = 6,
                            Nights = 2,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 7,
                            GuestId = 7,
                            Nights = 1,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 8,
                            GuestId = 8,
                            Nights = 4,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 9,
                            GuestId = 9,
                            Nights = 5,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 10,
                            GuestId = 10,
                            Nights = 3,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 11,
                            GuestId = 11,
                            Nights = 2,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 12,
                            GuestId = 12,
                            Nights = 1,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 13,
                            GuestId = 13,
                            Nights = 4,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 14,
                            GuestId = 14,
                            Nights = 5,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 15,
                            GuestId = 15,
                            Nights = 3,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 16,
                            GuestId = 16,
                            Nights = 2,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 17,
                            GuestId = 17,
                            Nights = 1,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 18,
                            GuestId = 18,
                            Nights = 4,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 19,
                            GuestId = 19,
                            Nights = 1,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 20,
                            GuestId = 20,
                            Nights = 3,
                            RoomId = 20
                        },
                        new
                        {
                            GuestRoomId = 21,
                            GuestId = 21,
                            Nights = 2,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 22,
                            GuestId = 22,
                            Nights = 1,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 23,
                            GuestId = 23,
                            Nights = 4,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 24,
                            GuestId = 24,
                            Nights = 5,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 25,
                            GuestId = 25,
                            Nights = 3,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 26,
                            GuestId = 26,
                            Nights = 2,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 27,
                            GuestId = 27,
                            Nights = 1,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 28,
                            GuestId = 28,
                            Nights = 4,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 29,
                            GuestId = 29,
                            Nights = 5,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 30,
                            GuestId = 30,
                            Nights = 3,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 31,
                            GuestId = 31,
                            Nights = 2,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 32,
                            GuestId = 32,
                            Nights = 1,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 33,
                            GuestId = 33,
                            Nights = 4,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 34,
                            GuestId = 34,
                            Nights = 5,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 35,
                            GuestId = 35,
                            Nights = 3,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 36,
                            GuestId = 36,
                            Nights = 2,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 37,
                            GuestId = 37,
                            Nights = 1,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 38,
                            GuestId = 38,
                            Nights = 4,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 39,
                            GuestId = 39,
                            Nights = 5,
                            RoomId = 1
                        },
                        new
                        {
                            GuestRoomId = 40,
                            GuestId = 40,
                            Nights = 3,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 41,
                            GuestId = 41,
                            Nights = 12,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 42,
                            GuestId = 42,
                            Nights = 1,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 43,
                            GuestId = 43,
                            Nights = 4,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 44,
                            GuestId = 44,
                            Nights = 5,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 45,
                            GuestId = 45,
                            Nights = 13,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 46,
                            GuestId = 46,
                            Nights = 2,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 47,
                            GuestId = 47,
                            Nights = 1,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 48,
                            GuestId = 48,
                            Nights = 4,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 49,
                            GuestId = 49,
                            Nights = 5,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 50,
                            GuestId = 50,
                            Nights = 3,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 51,
                            GuestId = 51,
                            Nights = 2,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 52,
                            GuestId = 52,
                            Nights = 1,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 53,
                            GuestId = 53,
                            Nights = 4,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 54,
                            GuestId = 54,
                            Nights = 5,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 55,
                            GuestId = 55,
                            Nights = 3,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 56,
                            GuestId = 56,
                            Nights = 2,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 57,
                            GuestId = 57,
                            Nights = 1,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 58,
                            GuestId = 58,
                            Nights = 4,
                            RoomId = 20
                        },
                        new
                        {
                            GuestRoomId = 59,
                            GuestId = 59,
                            Nights = 5,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 60,
                            GuestId = 60,
                            Nights = 3,
                            RoomId = 18
                        });
                });

            modelBuilder.Entity("Guestly.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.Property<string>("RoomNumber");

                    b.Property<string>("RoomType");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Price = 125,
                            RoomNumber = "105",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 2,
                            Price = 110,
                            RoomNumber = "110",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 3,
                            Price = 85,
                            RoomNumber = "111",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 4,
                            Price = 150,
                            RoomNumber = "188",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 5,
                            Price = 150,
                            RoomNumber = "190",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 6,
                            Price = 95,
                            RoomNumber = "210",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 7,
                            Price = 85,
                            RoomNumber = "211",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 8,
                            Price = 85,
                            RoomNumber = "215",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 9,
                            Price = 95,
                            RoomNumber = "220",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 10,
                            Price = 150,
                            RoomNumber = "237",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 11,
                            Price = 125,
                            RoomNumber = "279",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 12,
                            Price = 95,
                            RoomNumber = "311",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 13,
                            Price = 110,
                            RoomNumber = "333",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 14,
                            Price = 110,
                            RoomNumber = "345",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 15,
                            Price = 85,
                            RoomNumber = "366",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 16,
                            Price = 85,
                            RoomNumber = "369",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 17,
                            Price = 110,
                            RoomNumber = "375",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 18,
                            Price = 125,
                            RoomNumber = "380",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 19,
                            Price = 110,
                            RoomNumber = "387",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 20,
                            Price = 125,
                            RoomNumber = "399",
                            RoomType = "King"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Guestly.Models.GuestRoom", b =>
                {
                    b.HasOne("Guestly.Models.Guest", "Guest")
                        .WithMany("Rooms")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guestly.Models.Room", "Room")
                        .WithMany("Guests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
