// <auto-generated />
using System;
using Guestly.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Guestly.Migrations
{
    [DbContext(typeof(GuestlyContext))]
    [Migration("20210127230618_checkoutdates")]
    partial class checkoutdates
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Guestly.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Guestly.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<int>("LifetimeNights");

                    b.Property<int>("LifetimeRevenue");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("GuestId");

                    b.ToTable("Guests");

                    b.HasData(
                        new
                        {
                            GuestId = 1,
                            Email = "jd@email.com",
                            FirstName = "Jack",
                            LastName = "Daniel",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "1223334444"
                        },
                        new
                        {
                            GuestId = 2,
                            Email = "thisisdrew@email.com",
                            FirstName = "Drew",
                            LastName = "Mason",
                            LifetimeNights = 1,
                            LifetimeRevenue = 220,
                            PhoneNumber = "5673451231"
                        },
                        new
                        {
                            GuestId = 3,
                            Email = "matthewpatel@email.com",
                            FirstName = "Matthew",
                            LastName = "Patel",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "192837465"
                        },
                        new
                        {
                            GuestId = 4,
                            Email = "sethdoray@email.com",
                            FirstName = "Seth",
                            LastName = "Doray",
                            LifetimeNights = 5,
                            LifetimeRevenue = 750,
                            PhoneNumber = "5033505003"
                        },
                        new
                        {
                            GuestId = 5,
                            Email = "doublerich@email.com",
                            FirstName = "Richard",
                            LastName = "Richardson",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "9717717771"
                        },
                        new
                        {
                            GuestId = 6,
                            Email = "cal3b3dwards@email.com",
                            FirstName = "Caleb",
                            LastName = "Edwards",
                            LifetimeNights = 2,
                            LifetimeRevenue = 190,
                            PhoneNumber = "2736498710"
                        },
                        new
                        {
                            GuestId = 7,
                            Email = "volleyballrox@email.com",
                            FirstName = "Shoyo",
                            LastName = "Hinita",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "1133224433"
                        },
                        new
                        {
                            GuestId = 8,
                            Email = "rileykeys@email.com",
                            FirstName = "Riley",
                            LastName = "Keys",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "4252075079"
                        },
                        new
                        {
                            GuestId = 9,
                            Email = "heyyouparkit@email.com",
                            FirstName = "Parker",
                            LastName = "Wallenburger",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "5555599999"
                        },
                        new
                        {
                            GuestId = 10,
                            Email = "mydognigel@email.com",
                            FirstName = "Nigel",
                            LastName = "Dogo",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "3333333333"
                        },
                        new
                        {
                            GuestId = 11,
                            Email = "rickiede@email.com",
                            FirstName = "Rick",
                            LastName = "Ellis",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "4155558956"
                        },
                        new
                        {
                            GuestId = 12,
                            Email = "acathome@email.com",
                            FirstName = "Alex",
                            LastName = "Calder",
                            LifetimeNights = 1,
                            LifetimeRevenue = 95,
                            PhoneNumber = "5065558989"
                        },
                        new
                        {
                            GuestId = 13,
                            Email = "elbell@email.com",
                            FirstName = "Erica",
                            LastName = "Bell",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "9715558562"
                        },
                        new
                        {
                            GuestId = 14,
                            Email = "denicolab@email.com",
                            FirstName = "Bobby",
                            LastName = "DeNicola",
                            LifetimeNights = 5,
                            LifetimeRevenue = 550,
                            PhoneNumber = "7075559846"
                        },
                        new
                        {
                            GuestId = 15,
                            Email = "emmunoz@email.com",
                            FirstName = "Ellie",
                            LastName = "Munoz",
                            LifetimeNights = 3,
                            LifetimeRevenue = 255,
                            PhoneNumber = "5035556231"
                        },
                        new
                        {
                            GuestId = 16,
                            Email = "jmcteller@email.com",
                            FirstName = "Joshua",
                            LastName = "McTeller",
                            LifetimeNights = 2,
                            LifetimeRevenue = 170,
                            PhoneNumber = "4155558894"
                        },
                        new
                        {
                            GuestId = 17,
                            Email = "nnatell@email.com",
                            FirstName = "Natalie",
                            LastName = "Lass",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "5415558896"
                        },
                        new
                        {
                            GuestId = 18,
                            Email = "tridoublep@email.com",
                            FirstName = "Tripp",
                            LastName = "Ford",
                            LifetimeNights = 4,
                            LifetimeRevenue = 500,
                            PhoneNumber = "5035552483"
                        },
                        new
                        {
                            GuestId = 19,
                            Email = "wilford@email.com",
                            FirstName = "Willie",
                            LastName = "Ford",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "4155556472"
                        },
                        new
                        {
                            GuestId = 20,
                            Email = "katwoz@email.com",
                            FirstName = "Kaitlin",
                            LastName = "Wozniak",
                            LifetimeNights = 3,
                            LifetimeRevenue = 375,
                            PhoneNumber = "5035558258"
                        },
                        new
                        {
                            GuestId = 21,
                            Email = "madalynl11@email.com",
                            FirstName = "Madalyn",
                            LastName = "Lathem",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "6514553861"
                        },
                        new
                        {
                            GuestId = 22,
                            Email = "sean.mercado04@email.com",
                            FirstName = "Sean",
                            LastName = "Mercado",
                            LifetimeNights = 1,
                            LifetimeRevenue = 125,
                            PhoneNumber = "5018988936"
                        },
                        new
                        {
                            GuestId = 23,
                            Email = "viktoriaaksnes@email.com",
                            FirstName = "Viktoria",
                            LastName = "Nielsen",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "7843247148"
                        },
                        new
                        {
                            GuestId = 24,
                            Email = "now@email.com",
                            FirstName = "Nao",
                            LastName = "Oka",
                            LifetimeNights = 5,
                            LifetimeRevenue = 425,
                            PhoneNumber = "3193198947"
                        },
                        new
                        {
                            GuestId = 25,
                            Email = "bernie@mittens.com",
                            FirstName = "Bernie",
                            LastName = "Hancock",
                            LifetimeNights = 3,
                            LifetimeRevenue = 255,
                            PhoneNumber = "2778649180"
                        },
                        new
                        {
                            GuestId = 26,
                            Email = "pratte16@email.com",
                            FirstName = "Eleanor",
                            LastName = "Pratte",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "4529407334"
                        },
                        new
                        {
                            GuestId = 27,
                            Email = "aurorabergen@email.com",
                            FirstName = "Aurora",
                            LastName = "Berg",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "1338214188"
                        },
                        new
                        {
                            GuestId = 28,
                            Email = "mr.underhill@email.com",
                            FirstName = "Frodo",
                            LastName = "Baggins",
                            LifetimeNights = 4,
                            LifetimeRevenue = 380,
                            PhoneNumber = "5385970949"
                        },
                        new
                        {
                            GuestId = 29,
                            Email = "takanoart@email.com",
                            FirstName = "Aya",
                            LastName = "Takano",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "2969397018"
                        },
                        new
                        {
                            GuestId = 30,
                            Email = "deckard.rick@email.com",
                            FirstName = "Rick",
                            LastName = "Deckard",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "6192533993"
                        },
                        new
                        {
                            GuestId = 31,
                            Email = "happy_golfmore@email.com",
                            FirstName = "Happy",
                            LastName = "Gilmore",
                            LifetimeNights = 2,
                            LifetimeRevenue = 190,
                            PhoneNumber = "1234578900"
                        },
                        new
                        {
                            GuestId = 32,
                            Email = "joycesummers@email.com",
                            FirstName = "Joyce",
                            LastName = "Summers",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "1987899876"
                        },
                        new
                        {
                            GuestId = 33,
                            Email = "KHarm123@email.com",
                            FirstName = "Harmony",
                            LastName = "Kendall",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "1465768945"
                        },
                        new
                        {
                            GuestId = 34,
                            Email = "JennyCal@email.com",
                            FirstName = "Jenny",
                            LastName = "Calendar",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "2343546754"
                        },
                        new
                        {
                            GuestId = 35,
                            Email = "anointed1_66@email.com",
                            FirstName = "Annointed",
                            LastName = "One",
                            LifetimeNights = 3,
                            LifetimeRevenue = 450,
                            PhoneNumber = "6894562341"
                        },
                        new
                        {
                            GuestId = 36,
                            Email = "H.Sums@email.com",
                            FirstName = "Hank",
                            LastName = "Summers",
                            LifetimeNights = 2,
                            LifetimeRevenue = 300,
                            PhoneNumber = "1029384234"
                        },
                        new
                        {
                            GuestId = 37,
                            Email = "jessekmcjay@email.com",
                            FirstName = "Jesse",
                            LastName = "McNally",
                            LifetimeNights = 1,
                            LifetimeRevenue = 85,
                            PhoneNumber = "4675823123"
                        },
                        new
                        {
                            GuestId = 38,
                            Email = "JonLev@email.com",
                            FirstName = "Jonathan",
                            LastName = "Levinson",
                            LifetimeNights = 4,
                            LifetimeRevenue = 440,
                            PhoneNumber = "9858673452"
                        },
                        new
                        {
                            GuestId = 39,
                            Email = "eRayne@email.com",
                            FirstName = "Ethan",
                            LastName = "Rayne",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "2384655432"
                        },
                        new
                        {
                            GuestId = 40,
                            Email = "gottahavefaith@email.com",
                            FirstName = "Faith",
                            LastName = "Lehane",
                            LifetimeNights = 3,
                            LifetimeRevenue = 330,
                            PhoneNumber = "2349853456"
                        },
                        new
                        {
                            GuestId = 41,
                            Email = "notTaratino@email.com",
                            FirstName = "Quentin",
                            LastName = "Travers",
                            LifetimeNights = 12,
                            LifetimeRevenue = 1020,
                            PhoneNumber = "3458768676"
                        },
                        new
                        {
                            GuestId = 42,
                            Email = "scott!@email.com",
                            FirstName = "Scott",
                            LastName = "Hope",
                            LifetimeNights = 1,
                            LifetimeRevenue = 150,
                            PhoneNumber = "5436667534"
                        },
                        new
                        {
                            GuestId = 43,
                            Email = "asYouWish@email.com",
                            FirstName = "Wesley",
                            LastName = "Pryce",
                            LifetimeNights = 4,
                            LifetimeRevenue = 600,
                            PhoneNumber = "2345674564"
                        },
                        new
                        {
                            GuestId = 44,
                            Email = "PromQueen@email.com",
                            FirstName = "Cordelia",
                            LastName = "Chase",
                            LifetimeNights = 5,
                            LifetimeRevenue = 475,
                            PhoneNumber = "5543234321"
                        },
                        new
                        {
                            GuestId = 45,
                            Email = "OnlyBuffyWillJudge@email.com",
                            FirstName = "Buffy",
                            LastName = "Summers",
                            LifetimeNights = 13,
                            LifetimeRevenue = 1105,
                            PhoneNumber = "8778887634"
                        },
                        new
                        {
                            GuestId = 46,
                            Email = "Bookguy@email.com",
                            FirstName = "Rupert",
                            LastName = "Giles",
                            LifetimeNights = 2,
                            LifetimeRevenue = 170,
                            PhoneNumber = "4756566879"
                        },
                        new
                        {
                            GuestId = 47,
                            Email = "witchStuff@email.com",
                            FirstName = "Willow",
                            LastName = "Rosenberg",
                            LifetimeNights = 1,
                            LifetimeRevenue = 95,
                            PhoneNumber = "7998884475"
                        },
                        new
                        {
                            GuestId = 48,
                            Email = "jokesDotCom@email.com",
                            FirstName = "Xander",
                            LastName = "Harris",
                            LifetimeNights = 4,
                            LifetimeRevenue = 600,
                            PhoneNumber = "3334958679"
                        },
                        new
                        {
                            GuestId = 49,
                            Email = "BadBois@email.com",
                            FirstName = "William",
                            LastName = "Pratt",
                            LifetimeNights = 5,
                            LifetimeRevenue = 625,
                            PhoneNumber = "4445556634"
                        },
                        new
                        {
                            GuestId = 50,
                            Email = "ImaMouse@email.com",
                            FirstName = "Amy",
                            LastName = "Madison",
                            LifetimeNights = 3,
                            LifetimeRevenue = 285,
                            PhoneNumber = "2873345543"
                        },
                        new
                        {
                            GuestId = 51,
                            Email = "TwoNewtons@email.com",
                            FirstName = "Cassie",
                            LastName = "Newton",
                            LifetimeNights = 2,
                            LifetimeRevenue = 220,
                            PhoneNumber = "9987896786"
                        },
                        new
                        {
                            GuestId = 52,
                            Email = "Alternate@email.com",
                            FirstName = "Chao",
                            LastName = "Ahn",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "6675844776"
                        },
                        new
                        {
                            GuestId = 53,
                            Email = "SeattleResident@email.com",
                            FirstName = "Count",
                            LastName = "Dracula",
                            LifetimeNights = 4,
                            LifetimeRevenue = 340,
                            PhoneNumber = "9980987867"
                        },
                        new
                        {
                            GuestId = 54,
                            Email = "militarystuff@email.com",
                            FirstName = "Forrest",
                            LastName = "Gates",
                            LifetimeNights = 5,
                            LifetimeRevenue = 425,
                            PhoneNumber = "8009978865"
                        },
                        new
                        {
                            GuestId = 55,
                            Email = "Indiacohen@email.com",
                            FirstName = "India",
                            LastName = "Cohen",
                            LifetimeNights = 3,
                            LifetimeRevenue = 330,
                            PhoneNumber = "9078788986"
                        },
                        new
                        {
                            GuestId = 56,
                            Email = "janicePenshaw@email.com",
                            FirstName = "Janice",
                            LastName = "Penshaw",
                            LifetimeNights = 2,
                            LifetimeRevenue = 250,
                            PhoneNumber = "6678745632"
                        },
                        new
                        {
                            GuestId = 57,
                            Email = "KathyNewman@email.com",
                            FirstName = "Kathy",
                            LastName = "Newman",
                            LifetimeNights = 1,
                            LifetimeRevenue = 110,
                            PhoneNumber = "1122212345"
                        },
                        new
                        {
                            GuestId = 58,
                            Email = "KendraYoung@email.com",
                            FirstName = "Kendra",
                            LastName = "Young",
                            LifetimeNights = 4,
                            LifetimeRevenue = 500,
                            PhoneNumber = "4645534233"
                        },
                        new
                        {
                            GuestId = 59,
                            Email = "BeelzebubRules@email.com",
                            FirstName = "Hades",
                            LastName = "Beelzebub",
                            LifetimeNights = 5,
                            LifetimeRevenue = 550,
                            PhoneNumber = "6666666666"
                        },
                        new
                        {
                            GuestId = 60,
                            Email = "TheJenny@email.com",
                            FirstName = "Jenny",
                            LastName = "Jenny",
                            LifetimeNights = 3,
                            LifetimeRevenue = 375,
                            PhoneNumber = "2018675309"
                        });
                });

            modelBuilder.Entity("Guestly.Models.GuestRoom", b =>
                {
                    b.Property<int>("GuestRoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ArriveDate");

                    b.Property<string>("CheckoutDate");

                    b.Property<int>("GuestId");

                    b.Property<int>("Nights");

                    b.Property<int>("RoomId");

                    b.HasKey("GuestRoomId");

                    b.HasIndex("GuestId");

                    b.HasIndex("RoomId");

                    b.ToTable("GuestRoom");

                    b.HasData(
                        new
                        {
                            GuestRoomId = 1,
                            ArriveDate = "5/22/20",
                            CheckoutDate = "5/24/20",
                            GuestId = 1,
                            Nights = 2,
                            RoomId = 1
                        },
                        new
                        {
                            GuestRoomId = 2,
                            ArriveDate = "6/5/20",
                            CheckoutDate = "6/6/20",
                            GuestId = 2,
                            Nights = 1,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 3,
                            ArriveDate = "1/31/20",
                            CheckoutDate = "2/4/20",
                            GuestId = 3,
                            Nights = 4,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 4,
                            ArriveDate = "8/11/20",
                            CheckoutDate = "8/16/20",
                            GuestId = 4,
                            Nights = 5,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 5,
                            ArriveDate = "2/28/20",
                            CheckoutDate = "3/2/20",
                            GuestId = 5,
                            Nights = 3,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 6,
                            ArriveDate = "6/5/20",
                            CheckoutDate = "6/7/20",
                            GuestId = 6,
                            Nights = 2,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 7,
                            ArriveDate = "7/13/20",
                            CheckoutDate = "7/14/20",
                            GuestId = 7,
                            Nights = 1,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 8,
                            ArriveDate = "8/15/20",
                            CheckoutDate = "8/19/20",
                            GuestId = 8,
                            Nights = 4,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 9,
                            ArriveDate = "9/30/20",
                            CheckoutDate = "10/5/20",
                            GuestId = 9,
                            Nights = 5,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 10,
                            ArriveDate = "11/26/19",
                            CheckoutDate = "11/29/19",
                            GuestId = 10,
                            Nights = 3,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 11,
                            ArriveDate = "12/25/19",
                            CheckoutDate = "12/27/19",
                            GuestId = 11,
                            Nights = 2,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 12,
                            ArriveDate = "12/31/20",
                            CheckoutDate = "1/1/21",
                            GuestId = 12,
                            Nights = 1,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 13,
                            ArriveDate = "1/1/20",
                            CheckoutDate = "1/5/20",
                            GuestId = 13,
                            Nights = 4,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 14,
                            ArriveDate = "8/10/20",
                            CheckoutDate = "8/15/20",
                            GuestId = 14,
                            Nights = 5,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 15,
                            ArriveDate = "10/27/19",
                            CheckoutDate = "10/30/19",
                            GuestId = 15,
                            Nights = 3,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 16,
                            ArriveDate = "10/7/20",
                            CheckoutDate = "10/9/20",
                            GuestId = 16,
                            Nights = 2,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 17,
                            ArriveDate = "11/28/20",
                            CheckoutDate = "11/29/20",
                            GuestId = 17,
                            Nights = 1,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 18,
                            ArriveDate = "4/4/20",
                            CheckoutDate = "4/8/20",
                            GuestId = 18,
                            Nights = 4,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 19,
                            ArriveDate = "11/14/19",
                            CheckoutDate = "11/15/19",
                            GuestId = 19,
                            Nights = 1,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 20,
                            ArriveDate = "7/4/20",
                            CheckoutDate = "7/7/20",
                            GuestId = 20,
                            Nights = 3,
                            RoomId = 20
                        },
                        new
                        {
                            GuestRoomId = 21,
                            ArriveDate = "3/15/20",
                            CheckoutDate = "3/17/20",
                            GuestId = 21,
                            Nights = 2,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 22,
                            ArriveDate = "5/19/20",
                            CheckoutDate = "5/20/20",
                            GuestId = 22,
                            Nights = 1,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 23,
                            ArriveDate = "5/30/20",
                            CheckoutDate = "6/4/20",
                            GuestId = 23,
                            Nights = 4,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 24,
                            ArriveDate = "2/29/20",
                            CheckoutDate = "3/5/20",
                            GuestId = 24,
                            Nights = 5,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 25,
                            ArriveDate = "6/18/20",
                            CheckoutDate = "6/21/20",
                            GuestId = 25,
                            Nights = 3,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 26,
                            ArriveDate = "10/29/20",
                            CheckoutDate = "10/31/20",
                            GuestId = 26,
                            Nights = 2,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 27,
                            ArriveDate = "11/2/20",
                            CheckoutDate = "11/3/20",
                            GuestId = 27,
                            Nights = 1,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 28,
                            ArriveDate = "12/5/20",
                            CheckoutDate = "12/9/20",
                            GuestId = 28,
                            Nights = 4,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 29,
                            ArriveDate = "4/1/20",
                            CheckoutDate = "4/6/20",
                            GuestId = 29,
                            Nights = 5,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 30,
                            ArriveDate = "5/2/20",
                            CheckoutDate = "5/5/20",
                            GuestId = 30,
                            Nights = 3,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 31,
                            ArriveDate = "6/3/20",
                            CheckoutDate = "6/5/20",
                            GuestId = 31,
                            Nights = 2,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 32,
                            ArriveDate = "7/4/20",
                            CheckoutDate = "7/5/20",
                            GuestId = 32,
                            Nights = 1,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 33,
                            ArriveDate = "8/5/20",
                            CheckoutDate = "8/9/20",
                            GuestId = 33,
                            Nights = 4,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 34,
                            ArriveDate = "9/6/20",
                            CheckoutDate = "9/11/20",
                            GuestId = 34,
                            Nights = 5,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 35,
                            ArriveDate = "10/7/20",
                            CheckoutDate = "10/10/20",
                            GuestId = 35,
                            Nights = 3,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 36,
                            ArriveDate = "11/8/20",
                            CheckoutDate = "11/10/20",
                            GuestId = 36,
                            Nights = 2,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 37,
                            ArriveDate = "12/10/19",
                            CheckoutDate = "12/11/19",
                            GuestId = 37,
                            Nights = 1,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 38,
                            ArriveDate = "11/21/20",
                            CheckoutDate = "11/25/20",
                            GuestId = 38,
                            Nights = 4,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 39,
                            ArriveDate = "10/11/20",
                            CheckoutDate = "10/16/20",
                            GuestId = 39,
                            Nights = 5,
                            RoomId = 1
                        },
                        new
                        {
                            GuestRoomId = 40,
                            ArriveDate = "9/16/20",
                            CheckoutDate = "9/19/20",
                            GuestId = 40,
                            Nights = 3,
                            RoomId = 2
                        },
                        new
                        {
                            GuestRoomId = 41,
                            ArriveDate = "8/23/20",
                            CheckoutDate = "8/24/20",
                            GuestId = 41,
                            Nights = 1,
                            RoomId = 3
                        },
                        new
                        {
                            GuestRoomId = 42,
                            ArriveDate = "7/8/20",
                            CheckoutDate = "7/9/20",
                            GuestId = 42,
                            Nights = 1,
                            RoomId = 4
                        },
                        new
                        {
                            GuestRoomId = 43,
                            ArriveDate = "6/10/20",
                            CheckoutDate = "6/14/20",
                            GuestId = 43,
                            Nights = 4,
                            RoomId = 5
                        },
                        new
                        {
                            GuestRoomId = 44,
                            ArriveDate = "5/8/20",
                            CheckoutDate = "5/13/20",
                            GuestId = 44,
                            Nights = 5,
                            RoomId = 6
                        },
                        new
                        {
                            GuestRoomId = 45,
                            ArriveDate = "4/21/20",
                            CheckoutDate = "4/22/20",
                            GuestId = 45,
                            Nights = 1,
                            RoomId = 7
                        },
                        new
                        {
                            GuestRoomId = 46,
                            ArriveDate = "3/7/20",
                            CheckoutDate = "3/9/20",
                            GuestId = 46,
                            Nights = 2,
                            RoomId = 8
                        },
                        new
                        {
                            GuestRoomId = 47,
                            ArriveDate = "2/3/20",
                            CheckoutDate = "2/4/20",
                            GuestId = 47,
                            Nights = 1,
                            RoomId = 9
                        },
                        new
                        {
                            GuestRoomId = 48,
                            ArriveDate = "1/2/20",
                            CheckoutDate = "1/6/20",
                            GuestId = 48,
                            Nights = 4,
                            RoomId = 10
                        },
                        new
                        {
                            GuestRoomId = 49,
                            ArriveDate = "12/1/19",
                            CheckoutDate = "12/6/19",
                            GuestId = 49,
                            Nights = 5,
                            RoomId = 11
                        },
                        new
                        {
                            GuestRoomId = 50,
                            ArriveDate = "11/13/19",
                            CheckoutDate = "11/16/19",
                            GuestId = 50,
                            Nights = 3,
                            RoomId = 12
                        },
                        new
                        {
                            GuestRoomId = 51,
                            ArriveDate = "10/28/20",
                            CheckoutDate = "10/30/20",
                            GuestId = 51,
                            Nights = 2,
                            RoomId = 13
                        },
                        new
                        {
                            GuestRoomId = 52,
                            ArriveDate = "9/22/20",
                            CheckoutDate = "9/23/20",
                            GuestId = 52,
                            Nights = 1,
                            RoomId = 14
                        },
                        new
                        {
                            GuestRoomId = 53,
                            ArriveDate = "8/24/20",
                            CheckoutDate = "8/28/20",
                            GuestId = 53,
                            Nights = 4,
                            RoomId = 15
                        },
                        new
                        {
                            GuestRoomId = 54,
                            ArriveDate = "7/21/20",
                            CheckoutDate = "7/26/20",
                            GuestId = 54,
                            Nights = 5,
                            RoomId = 16
                        },
                        new
                        {
                            GuestRoomId = 55,
                            ArriveDate = "6/17/20",
                            CheckoutDate = "6/20/20",
                            GuestId = 55,
                            Nights = 3,
                            RoomId = 17
                        },
                        new
                        {
                            GuestRoomId = 56,
                            ArriveDate = "5/3/20",
                            CheckoutDate = "5/5/20",
                            GuestId = 56,
                            Nights = 2,
                            RoomId = 18
                        },
                        new
                        {
                            GuestRoomId = 57,
                            ArriveDate = "4/4/20",
                            CheckoutDate = "4/5/20",
                            GuestId = 57,
                            Nights = 1,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 58,
                            ArriveDate = "3/22/20",
                            CheckoutDate = "3/26/20",
                            GuestId = 58,
                            Nights = 4,
                            RoomId = 20
                        },
                        new
                        {
                            GuestRoomId = 59,
                            ArriveDate = "2/10/20",
                            CheckoutDate = "2/15/20",
                            GuestId = 59,
                            Nights = 5,
                            RoomId = 19
                        },
                        new
                        {
                            GuestRoomId = 60,
                            ArriveDate = "1/1/20",
                            CheckoutDate = "1/4/20",
                            GuestId = 60,
                            Nights = 3,
                            RoomId = 18
                        });
                });

            modelBuilder.Entity("Guestly.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Price");

                    b.Property<string>("RoomNumber");

                    b.Property<string>("RoomType");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Price = 125,
                            RoomNumber = "105",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 2,
                            Price = 110,
                            RoomNumber = "110",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 3,
                            Price = 85,
                            RoomNumber = "111",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 4,
                            Price = 150,
                            RoomNumber = "188",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 5,
                            Price = 150,
                            RoomNumber = "190",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 6,
                            Price = 95,
                            RoomNumber = "210",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 7,
                            Price = 85,
                            RoomNumber = "211",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 8,
                            Price = 85,
                            RoomNumber = "215",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 9,
                            Price = 95,
                            RoomNumber = "220",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 10,
                            Price = 150,
                            RoomNumber = "237",
                            RoomType = "Suite"
                        },
                        new
                        {
                            RoomId = 11,
                            Price = 125,
                            RoomNumber = "279",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 12,
                            Price = 95,
                            RoomNumber = "311",
                            RoomType = "Full"
                        },
                        new
                        {
                            RoomId = 13,
                            Price = 110,
                            RoomNumber = "333",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 14,
                            Price = 110,
                            RoomNumber = "345",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 15,
                            Price = 85,
                            RoomNumber = "366",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 16,
                            Price = 85,
                            RoomNumber = "369",
                            RoomType = "Baby"
                        },
                        new
                        {
                            RoomId = 17,
                            Price = 110,
                            RoomNumber = "375",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 18,
                            Price = 125,
                            RoomNumber = "380",
                            RoomType = "King"
                        },
                        new
                        {
                            RoomId = 19,
                            Price = 110,
                            RoomNumber = "387",
                            RoomType = "Queen"
                        },
                        new
                        {
                            RoomId = 20,
                            Price = 125,
                            RoomNumber = "399",
                            RoomType = "King"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Guestly.Models.GuestRoom", b =>
                {
                    b.HasOne("Guestly.Models.Guest", "Guest")
                        .WithMany("Rooms")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guestly.Models.Room", "Room")
                        .WithMany("Guests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Guestly.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
